#!/bin/bash

dir=$(cd $(dirname "$0") && pwd)

if [[ "$1" == "ssh" || "$1" == "journal" ]] ; then
	PREPEND="$PREPEND -it"
fi

args="$@"
docker run -v $dir/keys:/.ssh \
	-u $(id -g `whoami`) \
	-e FLEETCTL_TUNNEL=`cat $dir/.entry-node` \
	-e FLEETCTL_STRICT_HOST_KEY_CHECKING=false \
	-w / -e HOME="/" \
	-v $dir/services:/services \
	$PREPEND cstpdk/fleet bash -c \
	"eval \`ssh-agent\` &>/dev/null && \
	ssh-add /.ssh/do &>/dev/null && \
	fleetctl $args"
