#!/bin/bash
dir=$(cd $(dirname "$0") && pwd)
docker run -it \
	-v $dir/keys:/root/.ssh \
	-e DO_TOKEN=$(cat .do-token) \
	-e DO_KEY_ID=$(cat .do-key) \
	-v `pwd`:/app do-coreos \
	${@:-bash -c "eval \`ssh-agent\` && \
		ssh-add /root/.ssh/do && lein repl"}
